main:
  prefix: "&8[aBanker&8] "
  # Storage systems: flat || mysql
  storage-system: "flat"
  # MySQL database setup
  mysql:
    host: ""
    port: ""
    database: ""
    username: ""
    password: ""
  # You can find all the sounds here:
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  # They need to be inside this -> ""
  deposit-sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
  withdraw-sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
  enable-error: "&cPlugin disabled, something went wrong."
  gui-display-name:
    banker-main: "&0Banker"
    banker-deposit: "&0Banker - Deposit"
    banker-withdraw: "&0Banker - Withdraw"

discord:
  enabled: false
  bot-token: ""
  channel-id: ""
  min-amount: 5000

money:
  every-hours: 30
  interest-rate: 2.0
  loans-on: true
  loans:
    first-loan: 1000.0
    second-loan: 2500.0
    third-loan: 5000.0